version: '3.8'
services:
  service-central:
    build: .
    ports:
      - '8501:8501'
    environment:
      - HF_API_TOKEN=${HF_API_TOKEN}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
